- src/index.css
- src/pages/cart/cart.tsx
- src/pages/detail/detail.tsx
- src/pages/main/main.tsx
- src/pages/mypage/mypage.tsx
- src/pages/payment/payment.tsx
- src/router/mainRouter.tsx
- 메인 컨테이너 레이아웃 코드 리팩토링
- index.css 의 container 삭제
- 각자 페이지의 container 삭제
- mainRouter 디자인 구조 변경 (실제 디자인은 그대로)
- close #1
> Refactor: 메인 레이아웃 구조 변경

- package.json
- src/App.tsx
- src/style/styled.d.ts
- src/style/theme.ts
- yarn.lock
- #5 
- #5 
- 수정이 필요한 부분이 있으면 말씀해주세요.
> Chore: ThemeProvider 추가

- custom.d.ts
- package.json
- src/assets/arrow-down.svg
- src/components/template/payment/index.tsx
- src/hooks/useClickOutside.ts
- src/index.css
- src/pages/payment/payment.tsx
- src/style/payment/paymentAnimation.ts
- src/style/payment/paymentStyle.ts
- src/style/styled.d.ts
- src/style/theme.ts
- tsconfig.json
- yarn.lock
- close #8 
- close #8 
- 어떤게 공통으로 쓰일지 몰라서 일단 payment 폴더에 스타일을 모두 정의했습니다. 회의 후 수정하면 좋을 것 같습니다!
- 작업 하다가 요금 정보를 모두 오른쪽으로 보내는 게 더 나을 것 같다는 생각을 했습니다. 의견 부탁드립니다!
- 글씨 크기도 전반적으로 조금 더 키울까하는데 어떨까요?
- 추후에 컴포넌트 관심사 분리 작업 계획 있습니다.
> [UI] 결제 페이지 UI 구현

- src/components/layout/modal/accountModal.tsx
- src/components/layout/modal/joinModal.tsx
- src/components/layout/modal/loginModal.tsx
- src/components/template/account/Overlay.tsx
- src/components/template/account/SignIn.tsx
- src/components/template/account/SignUp.tsx
- src/index.css
- src/style/account/AccountStyle.ts
> Feat: 로그인/회원가입 UI 구현

- src/components/template/cart/CartCard.tsx
- src/components/template/cart/CartDetail.tsx
- src/components/template/cart/CartList.tsx
- src/components/template/cart/CartListController.tsx
- src/components/template/cart/index.tsx
- src/pages/cart/cart.tsx
- src/style/cart/cartStyle.ts
> 장바구니 UI 구현

- src/components/template/mypage/index.tsx
- src/components/template/mypage/reservationCard.tsx
- src/components/template/mypage/reservationList.tsx
- src/components/template/mypage/wishCard.tsx
- src/components/template/mypage/wishList.tsx
- src/pages/mypage/mypage.tsx
close #26 
- 예약내역
- 찜리스트
- 홍규님, 정아님 만들어놓으신거 재사용했습니다🙇‍♂️
> 마이페이지 UI 구현

- src/components/template/detail/DetailContainer.tsx
- src/components/template/detail/DetailImageContainer.tsx
- src/components/template/detail/GuestModal/guestAgeGroup.tsx
- src/components/template/detail/ImageSlideModal.tsx
#14 
- 게스트 모달 인원 수 0명일 경우 -버튼 누를 시 disable
- 이미지 모달 슬라이드로 변경
> Feature/#14 게스트 모달 disable 추가 / 이미지 모달 슬라이드 모달로 변경

- src/components/layout/header.tsx
- src/components/layout/modal/HeaderModal.tsx
- src/components/layout/modal/accountModal.tsx
- src/components/template/account/SignIn.tsx
- src/components/template/account/index.tsx
- src/constant.ts
- src/style/account/AccountStyle.ts
- src/style/header/headerStyle.ts
Close #47 
상단바 로그인/회원가입 모달 UI 구현
로그인 모달 밖 영역 클릭 시 닫기
>  상단바 로그인/회원가입 모달 UI 구현

- src/api/service.ts
- src/components/layout/modal/accountModal.tsx
- src/components/template/account/SignIn.tsx
- src/components/template/account/SignUp.tsx
- src/components/template/account/index.tsx
- src/components/template/cart/CartCard.tsx
- src/components/template/cart/CartList.tsx
- src/components/template/cart/index.tsx
- src/constant.ts
- src/interfaces/interface.ts
- src/mocks/handlers.ts
close #62 
- 로그인/회원가입 API 적용
- 장바구니 API 적용
- 장바구니 체크된 리스트 배열 생성
> 로그인/회원가입 API & Cart API 적용

- src/components/template/main/index.tsx
Remove: 테스트 로그인 버튼 삭제
Remove: 테스트 로그인 버튼 삭제
> Remove: 테스트 로그인 버튼 삭제

- src/api/service.ts
- src/components/template/products/ProductsContainer.tsx
- src/hooks/useReservations.ts
- src/interfaces/interface.ts
> 룸카드, 숙소상세 모달 API적용

- src/api/service.ts
- src/components/template/payment/PaymentReservations.tsx
- src/components/template/payment/PaymentRoomItem.tsx
- src/components/template/payment/PaymentRoomList.tsx
- src/interfaces/interface.ts
> Feat: API 수정

- src/api/service.ts
- src/components/template/account/SignIn.tsx
- src/components/template/account/SignUp.tsx
- src/style/account/AccountStyle.ts
- src/util/util.ts
close #79 
쿠키 저장, prefix 에러 수정
> 쿠키 저장, prefix 에러 수정

- src/api/service.ts
- src/components/template/main/index.tsx
#64
쿼리스트링 category 값으로 getProductsCategory 실행 
결과값 없을 경우 결과 없음 메세지 렌더 
헤더 카테고리 디폴트로 선택되어 있는 상태(관광호텔) 해제해야 명확할 것 같습니다
> 메인 숙소정보 카테고리 API 적용

- src/components/template/mypage/reservationAccordion.tsx
- src/components/template/mypage/reservationCard.tsx
- src/components/template/products/ProductsContainer.tsx
- src/components/template/products/RoomCard.tsx
- src/components/template/products/detailModal/detailModal.tsx
- src/interfaces/interface.ts
- #97 
숙소상세보기 데이터패칭, UI 리팩토링 
- 지영님 맵핑👍
> 숙소상세보기 데이터패칭, UI 리팩토링 

- src/api/service.ts
- src/components/layout/modal/ModalContainer.tsx
- src/components/template/products/AllFacility.tsx
- src/components/template/products/FacilityModal.tsx
- src/components/template/products/ModalTab.tsx
- src/components/template/products/NoticeModal.tsx
- src/style/products/productsStyle.ts
#58(close된 이슈 보완)
- 모달 탭 형태로 변경
- 이용안내 내용 추가
> 편의시설 모달 탭모달로 변경(이용안내/편의시설)

- src/api/service.ts
- src/components/layout/PrivateRoute.tsx
- src/components/layout/modal/HeaderModal.tsx
- src/components/template/cart/EmptyCart.tsx
- src/components/template/cart/index.tsx
- src/router/mainRouter.tsx
- src/util/util.ts
#101 
로그아웃 API 적용, PrivateRoute 생성, loading 구현
> 로그아웃 API 적용, PrivateRoute 생성

- src/constant.ts
> Env: 환경변수 설정

- src/components/template/main/index.tsx
> Fix: 배포오류수정

- package.json
- src/components/template/main/index.tsx
- vite.config.ts
- yarn.lock
> Fix: 메인페이지 데이터패칭 예외처리 추가

- index.html
> Fix: main.tsx 경로에러 해결

- src/components/template/main/index.tsx
> Fix: 리액트쿼리로 변경

- src/components/template/main/index.tsx
> Fix: 조건부랜더링 변경

- src/components/template/main/index.tsx
> Fix: isArray 추가

- src/components/template/main/index.tsx
- vite.config.ts
> Env: 콘솔로그 다시표시

- src/api/service.ts
- src/components/template/main/index.tsx
- src/components/template/mypage/reservationAccordion.tsx
- src/components/template/mypage/reservationCard.tsx
- src/components/template/mypage/reviewWriteModal.tsx
- src/constant.ts
- src/interfaces/interface.ts
> 마이페이지 예약내역에서 리뷰작성 구현

- src/api/service.ts
- src/components/template/payment/PaymentDetail.tsx
- src/components/template/payment/PaymentReservations.tsx
- src/components/template/payment/PaymentRoomList.tsx
- src/components/template/payment/PaymentTerms.tsx
- src/components/template/payment/index.tsx
- src/components/template/payment/paymentConfirm/StyledPaymentConfirm.ts
- src/components/template/payment/paymentConfirm/index.tsx
- src/router/mainRouter.tsx
> 결제 로직 사이드 이펙트 제거 및 숙박 일 당 가격 계산

- src/components/template/main/category/MainCategory.tsx
> Fix: 기본 카테고리 값 없애기

- src/api/service.ts
- src/components/template/cart/CartCard.tsx
- src/components/template/products/RoomCard.tsx
close #142 
- 상품 바로 예약 시 장바구니 개수 업데이트
- 장바구니에서 체크 후 삭제 시  체크된 상품 리스트에서도 삭제되도록 수정
> Refactor: 상품 바로 예약 시 장바구니 개수 업데이트 & 장바구니 수정

- README.md
> Env: 최종 배포

- src/components/template/products/AccommodationInfo.tsx
- src/components/template/products/AllFacility.tsx
- src/components/template/products/ModalTab.tsx
- src/components/template/products/ProductsContainer.tsx
- src/components/template/products/Review.tsx
- src/components/template/products/RoomCard.tsx
- src/components/template/products/detailModal/detailModal.tsx
- src/components/template/products/detailModal/modalReview.tsx
- src/components/template/products/iconAndTextMapping.tsx
- src/hooks/useDisplayedReview.ts
- src/interfaces/interface.ts
- src/style/products/productsStyle.ts
- src/util/reviewUtilities.tsx
#154 
- 리뷰 평점 표시
- 상단 리뷰 클릭 시 리뷰 영역으로 스크롤 이동 
- 별표 반 개 표시
- 아이콘 매핑 key 값 수정
> 상품 상세 페이지 관련 리팩토링

- src/hooks/useDisplayedReview.ts
- src/util/reviewUtilities.tsx
> Fix: 배열 확인 조건 추가

- src/api/service.ts
- src/components/template/mypage/reservationAccordion.tsx
- src/components/template/mypage/reservationCard.tsx
- src/components/template/mypage/reviewWriteModal.tsx
- src/components/template/products/ProductsContainer.tsx
- src/interfaces/interface.ts
- src/util/util.ts
> 리뷰 수정, 삭제 구현

- src/components/template/mypage/reservationCard.tsx
> Fix: reservationCard.tsx data확인후 ui 렌더링

- src/components/template/account/SignIn.tsx
- src/util/util.ts
> Fix: 로그인 오류 수정

- src/components/layout/modal/DatePicker.tsx
- src/components/layout/modal/MapSearch.tsx
> 미사용 코드 정리 

- package.json
- src/components/template/payment/PaymentDetail.tsx
- src/components/template/payment/PaymentOptions.tsx
- src/components/template/payment/PaymentReservations.tsx
- src/components/template/payment/PaymentRoomList.tsx
- src/components/template/payment/index.tsx
- src/components/template/payment/paymentConfirm/index.tsx
- src/components/template/payment/utils/calculateNights.ts
- src/components/template/payment/utils/index.ts
- src/hooks/useFilteredReservation.ts
- src/pages/payment/ErrorFallback.tsx
- src/pages/payment/payment.tsx
- yarn.lock
> Feat: 결제 시스템 Error Boundary & Suspense 적용

- src/components/template/mypage/reservationAccordion.tsx
- src/components/template/mypage/reservationList.tsx
- src/components/template/mypage/reviewWriteModal.tsx
- react.memo 사용해서 리렌더링 제거
- useRef 사용해서 리뷰 텍스트 입력시 리렌더링 제거
> Refetor: 리뷰페이지 리렌더링 제거

- src/components/layout/modal/MapModal.tsx
- src/components/layout/modal/calenderModal.tsx
- src/components/template/products/ProductsContainer.tsx
- src/router/mainRouter.tsx
> Chore: 성능체크를 위한 롤백

- src/components/layout/modal/MapModal.tsx
- src/components/layout/modal/calenderModal.tsx
- src/components/template/products/ProductsContainer.tsx
- src/router/mainRouter.tsx
> Chore: 코드스플리팅 롤백

- src/components/layout/modal/MapModal.tsx
- src/components/layout/modal/calenderModal.tsx
- src/components/template/products/ProductsContainer.tsx
- src/router/mainRouter.tsx
> Chore: 번들링 최적화 재적용
